services:
  chatgpt2api-reg:
    image: ghcr.io/flyljx/regs:latest
    container_name: chatgpt2api-reg
    depends_on:
      - flaresolverr
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Shanghai
      CHATGPT2API_REG_APP_ROOT: /app/reg
    volumes:
      - ./:/app
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      TZ: Asia/Shanghai
      LOG_LEVEL: info
      LOG_HTML: "false"
      CAPTCHA_SOLVER: none
    ports:
      - "8191:8191"
    restart: unless-stopped
